Repository junsikshim/react-pane-system, pull requests merged in 2024-04, with the labels that each got.

#16 Reduce paneSystem logic duplication
  src/PaneSystem.tsx
Labels: refactoring

#21 Apply eslint
  .eslintrc.json
  package.json
  pnpm-lock.yaml
Labels: refactoring

#20 Separate splitters into a layer.
  .eslintrc.json
  .storybook/main.ts
  package.json
  pnpm-lock.yaml
  src/Pane.tsx
  src/PaneRow.tsx
  src/PaneSystem.tsx
  src/SplitterLayer.tsx
  src/hooks/useDelayedHover.tsx
  src/hooks/useResizableRef.tsx
  src/registry/PaneSystemPresenceContextRegistry.tsx
  src/registry/PaneSystemRectContext.tsx
  src/splitter/PaneRowSplitter.tsx
  src/splitter/PaneSplitter.tsx
  src/splitter/SplitterIntersectionHandle.tsx
  src/splitter/SplitterRegistry.tsx
  src/types.ts
  src/utils.ts
Labels: enhancement, refactoring

#25 Fix splitter going out of bounds.
  src/PaneSystem.tsx
Labels: bug

#27 Fix regex for floats.
  src/utils.ts
Labels: bug
